### ISSUE TITLE
Grunt should break execution on template errors + dext parameter

### ISSUE THREAD

**Issue by ddosoff** [SnakeskinTpl/grunt-snakeskin#1]
Please change in the function cb:

if (err) {
  grunt.fatal(err, 4);
}

Please add parameter dext for compiled templates like this:

opts = Object.assign({eol: '\n', dext: '.html'}, opts);

and use it when creating files:

if (p.exec) {
  savePath = path.join(savePath, path.basename(src, path.extname(src)) + opts.dext);

**Comment by kobezzza** [comment]
Ok, will fix soon!

**Comment by ddosoff** [comment]
BTW you did huge and awesome work!

**Comment by kobezzza** [comment]
Done.

**Comment by ddosoff** [comment]
Contact me on telegram pls t.me/chatbro
